name = "learn-mandarin"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "learn-mandarin"
database_id = "6433a24e-e498-4064-a55d-06aeeafaafda"
preview_database_id = "ca751137-9eef-4571-b636-84fa25d21767"
